### PR TITLE
Support for plans, explorative and theoretical research

### LINKED ISSUE #3: Support for plans, explorative and theoretical research
```
{
  "Q131841": "Idea",
  "Q1371819": "Plan",
  "Q17737": "Theory",
  "Q2412849": "Literature review",
  "Q321703": "Premise",
  "Q41719": "Hypothesis",
  "Q748250": "Prediction",
  "Q94535766": "Claim",
  "Q185698": "Methodology",
  "Q82604": "Design",
  "Q41689629": "Procedure",
  "Q16798631": "Equipment",
  "Q42848": "Data",
  "Q1070421": "Script",
  "Q1347572": "Evidence",
  "Q217602": "Analysis",
  "Q17104930": "Outcome",
  "Q3030248": "Discussion",
  "Q333291": "Abstract",
  "Q1318295": "Narrative",
  "Q604733": "Presentation",
  "Q265158": "Review",
  "Q55107540": "Other"
}
```

Submitting as issue as I don't have write access. @chartgerink could you sort that out or create a PR?

For Hypergraph this would currently imply that we'd need to reduce the (font) size of the content type dropdown list to make this usable. I do have reason to believe that all these would be valuable, especially to non-empirical researchers, and would likely also inspire users to publish more than just what would traditionally go into a paper.

### PR DESCRIPTION
**Pull request by jameslibscie**
For Hypergraph this would currently imply that we'd need to reduce the (font) size of the content type dropdown list to make this usable. I'm going to try some things out to see if that works.

I do have reason to believe that all these would be valuable, especially to non-empirical researchers, and would likely also inspire users to publish more than just what would traditionally go into a paper.

Closes #3

### CODE REVIEW

**Comment by jameslibscie** [comment]
See https://github.com/hypergraph-xyz/desktop/pull/238 for these content types in action.

**Review by juliangruber — APPROVED** [review]

**Review by chartgerink — APPROVED** [review]
Looks good :) 

Wonder how people will respond as the organisation of the list is implicit, but we'll figure that out as we go along.

**Comment by chartgerink** [comment]
Only one question remains after checking the exact Wikidata IDs: The "Claim" links to "Assertion" on wikidata. Could you explain a bit more about this? 

It might become confusing to have inconsistencies between wikidata and our presentation, but want to doublecheck whether this is a mistake or a conscious choice.

**Comment by jameslibscie** [comment]
I used the word "claim" as that was the starting point for the search for an appropriate wikidata entry. Wikidata lists "claim" as an alias for "assertion". I would also be fine with changing the text to assertion for consistency as I think we use the main definition for all other entries. And I also presume that "assertion" would be understood by those who are looking for "claim".

**Comment by jameslibscie** [comment]
@juliangruber Could you handle the release for this?

**Comment by juliangruber** [comment]
Sure! I'm off today and tomorrow but will do so on Friday

**Comment by juliangruber** [comment]
https://github.com/hypergraph-xyz/wikidata-identifiers/releases/tag/v1.2.0

**Pull request merged**
